import { Ticket } from "@/lib/tickets/types";

export const tickets: Ticket[] = [
    {
        id: "TCK-1016",
        title: "Adding a payment methods",
        userName: "Mitchel Marsh",
        email: "mitchel22@gmail.com",
        status: "open",
        priority: "low",
        createdAt: "2025-12-29T22:40:00Z",
        messagesCount: 3,
    },
    {
        id: "TCK-1017",
        title: "Duplicate charge issue",
        userName: "Kaveh Nouri",
        email: "kaveh.n@gmail.com",
        status: "pending",
        priority: "high",
        createdAt: "2025-12-29T21:15:00Z",
        messagesCount: 6,
    },
    {
        id: "TCK-1018",
        title: "Dashboard widgets not customizable",
        userName: "Zahra Mousavi",
        email: "zahra.m@gmail.com",
        status: "closed",
        priority: "low",
        createdAt: "2025-12-29T18:00:00Z",
        messagesCount: 2,
    },
    {
        id: "TCK-1019",
        title: "Mobile menu overlaps content",
        userName: "Pouya Bahrami",
        email: "p.bahrami@gmail.com",
        status: "open",
        priority: "medium",
        createdAt: "2025-12-29T15:30:00Z",
        messagesCount: 4,
    },
    {
        id: "TCK-1020",
        title: "Session expires too fast",
        userName: "Hamed Jalili",
        email: "hamed.j@gmail.com",
        status: "pending",
        priority: "medium",
        createdAt: "2025-12-29T13:50:00Z",
        messagesCount: 3,
    },
    {
        id: "TCK-1021",
        title: "Cannot reset password",
        userName: "Sara Karimi",
        email: "sara.k@gmail.com",
        status: "open",
        priority: "high",
        createdAt: "2022-01-29T12:40:00Z",
        messagesCount: 5,
    },
    {
        id: "TCK-1022",
        title: "Notifications not received",
        userName: "Ali Rezaei",
        email: "ali.r@gmail.com",
        status: "pending",
        priority: "medium",
        createdAt: "2024-10-29T11:30:00Z",
        messagesCount: 2,
    },
    {
        id: "TCK-1023",
        title: "Profile picture upload fails",
        userName: "Neda Farhadi",
        email: "neda.f@gmail.com",
        status: "open",
        priority: "low",
        createdAt: "2025-12-29T10:15:00Z",
        messagesCount: 1,
    },
    {
        id: "TCK-1024",
        title: "Billing page loads slowly",
        userName: "Arman Taheri",
        email: "arman.t@gmail.com",
        status: "open",
        priority: "medium",
        createdAt: "2025-12-29T09:45:00Z",
        messagesCount: 4,
    },
    {
        id: "TCK-1025",
        title: "Export to CSV not working",
        userName: "Maryam Hosseini",
        email: "maryam.h@gmail.com",
        status: "closed",
        priority: "low",
        createdAt: "2025-12-29T08:30:00Z",
        messagesCount: 2,
    },
    {
        id: "TCK-1026",
        title: "Two-factor authentication issue",
        userName: "Reza Moradi",
        email: "reza.m@gmail.com",
        status: "pending",
        priority: "high",
        createdAt: "2025-12-29T07:55:00Z",
        messagesCount: 6,
    },
    {
        id: "TCK-1027",
        title: "Dark mode flickers",
        userName: "Elham Shiri",
        email: "elham.s@gmail.com",
        status: "open",
        priority: "low",
        createdAt: "2025-12-29T06:40:00Z",
        messagesCount: 1,
    },
    {
        id: "TCK-1028",
        title: "User invited but cannot login",
        userName: "Mohsen Ghaemi",
        email: "mohsen.g@gmail.com",
        status: "pending",
        priority: "medium",
        createdAt: "2025-12-29T05:20:00Z",
        messagesCount: 3,
    },
    {
        id: "TCK-1029",
        title: "Webhook not triggered",
        userName: "Fatemeh Razi",
        email: "fatemeh.r@gmail.com",
        status: "open",
        priority: "high",
        createdAt: "2025-12-29T04:10:00Z",
        messagesCount: 5,
    },
    {
        id: "TCK-1030",
        title: "Language not switching",
        userName: "Sina Yazdani",
        email: "sina.y@gmail.com",
        status: "closed",
        priority: "low",
        createdAt: "2025-12-29T03:00:00Z",
        messagesCount: 2,
    },
    {
        id: "TCK-1031",
        title: "Search indexing delay",
        userName: "Parisa Ebrahimi",
        email: "parisa.e@gmail.com",
        status: "pending",
        priority: "medium",
        createdAt: "2025-12-29T02:30:00Z",
        messagesCount: 3,
    },
    {
        id: "TCK-1032",
        title: "Payment gateway timeout",
        userName: "Hossein Azadi",
        email: "hossein.a@gmail.com",
        status: "open",
        priority: "high",
        createdAt: "2025-12-29T01:40:00Z",
        messagesCount: 7,
    },
    {
        id: "TCK-1033",
        title: "UI breaks on Safari",
        userName: "Niloufar Kazemi",
        email: "niloufar.k@gmail.com",
        status: "pending",
        priority: "medium",
        createdAt: "2025-12-29T00:50:00Z",
        messagesCount: 4,
    },
    {
        id: "TCK-1034",
        title: "Account deletion request",
        userName: "Omid Rahmani",
        email: "omid.r@gmail.com",
        status: "closed",
        priority: "low",
        createdAt: "2025-12-28T23:30:00Z",
        messagesCount: 1,
    },
    {
        id: "TCK-1035",
        title: "Email verification link expired",
        userName: "Shayan Lotfi",
        email: "shayan.l@gmail.com",
        status: "open",
        priority: "medium",
        createdAt: "2025-12-28T22:10:00Z",
        messagesCount: 2,
    },
];
